<a href="https://colab.research.google.com/github/wangga03/Hi/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import tensorflow as tf

In [20]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [21]:
scalar.ndim

0

In [22]:
vector = tf.constant([[1,2,3],
                      [4,5,6]])

In [23]:
vector.ndim

2

In [24]:
tensor = tf.constant([[[3,4,3],[4,5,3], [3,3,3]],
                      [[3,3,3], [4,4,4], [4,4,4]],
                     [[2,2,2], [3,3,3], [4,4,4]]]
                     )
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[3, 4, 3],
        [4, 5, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [4, 4, 4],
        [4, 4, 4]],

       [[2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]], dtype=int32)>

In [25]:
tensor.ndim

3