<a href="https://colab.research.google.com/github/wangga03/Hi/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of tensor (ndim)
scalar.ndim

0

In [7]:
# Create a vector
vector = tf.constant([[1,2,3],
                      [4,5,6]])

vector

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [10]:
# Check the dimension of tensor
vector.ndim

2

In [11]:
# Create a matrix

matrix = tf.constant([[10, 7],
                      [10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [13]:
matrix.ndim

2

In [14]:
# Create a tensor
tensor = tf.constant([[[3,4,3],[4,5,3], [3,3,3]],
                      [[3,3,3], [4,4,4], [4,4,4]],
                     [[2,2,2], [3,3,3], [4,4,4]]]
                     )
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[3, 4, 3],
        [4, 5, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [4, 4, 4],
        [4, 4, 4]],

       [[2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]], dtype=int32)>

In [18]:
tensor.ndim

3

In [26]:
tensor2 = tf.constant([ [[1, 2, 3,4],[5, 6, 7,4]],
                        [[1, 2, 3,4], [3, 4, 5,4]],
                        [[3, 4, 5,4], [3, 4, 5,4]],
                        [[2, 3, 4,4], [3,4,5,4]]
                       ])
tensor2

<tf.Tensor: shape=(4, 2, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [5, 6, 7, 4]],

       [[1, 2, 3, 4],
        [3, 4, 5, 4]],

       [[3, 4, 5, 4],
        [3, 4, 5, 4]],

       [[2, 3, 4, 4],
        [3, 4, 5, 4]]], dtype=int32)>

In [27]:
tensor2.ndim

3